version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:6.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

#  trino:
#    image: trinodb/trino:351
#    ports:
#      - "8282:8080"
#    environment:
#      - TRINO_JAVA_OPTIONS=-Xmx2g
#      - TRINO_HEAP_SIZE=2g
#      - TRINO_MAX_DIRECT_MEMORY_SIZE=2g

  postgresql:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal

  temporal:
    image: temporalio/auto-setup:1.18.1
    depends_on:
      - postgresql
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql

  temporal-ui:
    depends_on:
      - temporal
    image: temporalio/ui:2.7.1
    ports:
      - "8383:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000

#  zeppelin:
#    image: apache/zeppelin:0.9.0
#    environment:
#      - ZEPPELIN_LOG_DIR=/logs
#      - ZEPPELIN_NOTEBOOK_DIR=/notebook
#    ports:
#      - "8484:8080"
#    volumes: # to persist our data once we've destroyed our containers
#      - ./notebook:/notebook
#      - ./logs:/logs
